spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/CHAPCHAP
    username: root
    password: ${db.password}
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  servlet:
    multipart:
      location: ${user.dir}/ChapChapServiceProject/src/main/resources/static/public/img
      max-file-size: 1MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: fhrzl55040@gmail.com
    #password : gmail 아이디 비밀번호가 아니라 2차 인증 어플리케이션 인증 받은 번호를 넣어야 한다.
    password: ${email.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
static:
  path: ${user.dir}/ChapChapServiceProject/src/main/resources/static

server:
  port: 9090
mybatis:
  type-aliases-package: com.acorn.chapspring.dto
  mapper-locations: mapper/*Mapper.xml
