spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/chapchap
    username: root
    password: ${db.password}

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  servlet:
    multipart:
      location: ${user.dir}/ChapChapServiceProject/src/main/resources/static/public/img
      max-file-size: 1MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: fhrzl55040@gmail.com
    #password : gmail 아이디 비밀번호가 아니라 2차 인증 어플리케이션 인증 받은 번호를 넣어야 한다.
    password: ${email.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 요청 uri
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰을 발급받기 위한 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me # 유저 정보를 받아오기 위한 uri
        registration:
          naver:
            client-id: 0EoGP7ojlGpxnQ2WYuPf
            client-secret: XeQl6Bbd3G
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/naver
            scope:
              - email
              - nickname

static:
  path: ${user.dir}/ChapChapServiceProject/src/main/resources/static
img:
  upload:
    path: ${user.dir}/ChapChapServiceProject/src/main/resources/static/public/img
server:
  port: 9090
mybatis:
  type-aliases-package: com.acorn.chapspring.dto
  mapper-locations: mapper/*Mapper.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count:countSql