spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/CHAPCHAP
    username: root
    password: mysql123
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:
      host: smtp.gmail.com
      port: 587
      username: fhrzl55040@gmail.com
      password: Yw71088923?!!
      properties:
        mail:
          smtp:
            starttls:
              enable: true
            auth: true


servlet:
  multipart:
    location: ${user.dir}/ChapChapServiceProject/src/main/resources/static/public/img
    max-file-size: 1MB
    max-request-size: 5MB
img:
  upload:
    path: ${user.dir}/ChapChapServiceProject/src/main/resources/static/public/img
static:
  path: ${user.dir}/ChapChapServiceProject/src/main/resources/static

server:
  port: 8080
mybatis:
  type-aliases-package: com.example.chapchapserviceproject.dto
  mapper-locations: mapper/*Mapper.xml
